name: Deploy to GCP Compute Engine
on:
  workflow_run:
    workflows: ["CI, build docker image and push that"]
    types:
      - completed

jobs:
  deploy-to-gce:
    runs-on: ubuntu-22.04

    steps:
    - name: Deploy to GCE via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "➡️ Authenticating gcloud (optional if instance has IAM role)"
          gcloud auth login --brief || echo "Already authenticated"
  
          echo "➡️ Configuring docker credential helper"
          yes | gcloud auth configure-docker asia-northeast3-docker.pkg.dev
  
          echo "➡️ Pulling Docker image from Artifact Registry"
          docker pull asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_NAME }}/${{ secrets.GCP_AR_NAME }}/knuclface:latest
  
          echo "🛑 Stopping old container if exists"
          docker stop knuclface-app || true
          docker rm knuclface-app || true
  
          echo "🚀 Running new container"
          docker run -d -p 8080:8080 --name knuclface-app \
            asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_NAME }}/${{ secrets.GCP_AR_NAME }}/knuclface:latest
