name: 'Deploy to Cloud Run'

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI, build docker image and push that"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1. 서비스 계정 인증
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CLOUR_RUN_ACCOUNT_KEY }}

      # 2. gcloud CLI 설치
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_NAME }}

      # 3. Cloud Run에 배포
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: knuclface-service
          image: asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_NAME }}/${{ secrets.GCP_AR_NAME }}/knuclface:latest
          region: asia-northeast3
          credentials: ${{ secrets.GCP_CLOUR_RUN_ACCOUNT_KEY }}
